import Dimens from '@base/common/Dimens';
import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {
    backgroundColor: '#fbfbfb',
    flex: 1,
    color: 'rgba(0, 0, 0, 0.85)',
    fontSize: 14,
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
    lineHeight: 15,
  },
  content: {
    paddingHorizontal: 15,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#f5422a',
    color: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 20,
    paddingTop: 40,
  },
  icon: {
    color: '#fff',
  },
  headerName: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 18,
    lineHeight: 24,
  },
  telecomBox: {
    backgroundColor: '#f1f1f1',
    borderRadius: 4,
    marginTop: 40,
    padding: 25,
    width: '100%',
  },
  telecomBox_exchange: {
    marginTop: 10,
  },
  telecomBox_exchange_value: {
    backgroundColor: '#fff',
    borderRadius: 4,
    color: '#ee0033',
    fontSize: 20,
    lineHeight: 30,
    padding: 12,
    textAlign: 'center',
  },
  telecomBox_exchange_value_strong: {
    fontSize: 24,
    fontWeight: '600',
    lineHeight: 32,
  },
  telecomBox__list: {
    marginTop: 20,
  },
  telecomBox_sub: {
    color: '#424242',
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 28,
    marginBottom: 8,
  },
  telecomBox_detail: {},
  telecomBox_value: {
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 20,
    marginTop: 5,
  },
  exchangePoint: {
    marginTop: 20,
  },
  exchangePoint__title: {
    fontSize: 24,
    marginBottom: 10,
    color: '#26292b',
    fontWeight: '600',
  },
  exchangePoint__list: {
    marginTop: 10,
    flexDirection: 'row',
    height: 200,
  },
  exchangePoint_item: {
    marginRight: 10,
    width: 170,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e7e7e7',
    borderRadius: 4,
    // overflow: 'hidden',
  },
  exchangePoint_item_images: {
    height: 140,
    position: 'relative',
    width: '100%',
  },
  img: {
    width: '100%',
    height: '100%',
  },
  exchangePoint_item_value: {
    position: 'absolute',
    top: '15%',
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  exchangePoint_item_value_title: {
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 40,
    lineHeight: 50,
    textAlign: 'center',
    color: '#ffffff',
  },
  exchangePoint_item_value_subtitle: {
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 40,
    lineHeight: 40,
    textAlign: 'center',
    color: '#ffffff',
  },
  exchangePoint_info: {
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  exchangePoint_icon: {
    color: '#ee0033',
    marginRight: 5,
  },
  exchangePoint_name: {
    color: '#26292b',
    fontSize: 16,
    fontWeight: '600',
    lineHeight: 24,
  },
  // modal
  modalContent: {
    backgroundColor: 'white',
    padding: 20,
    borderRadius: 4,
  },
  containerModal: {
    // flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modal: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#0000004a',
    padding: 20,
    paddingTop: 100,
  },
  text: {
    color: '#3f2949',
    marginTop: 10,
  },
  modal_endow: {
    // textAlign: 'center',
  },
  modalClose: {},
  modalCloseIcon: {
    textAlign: 'right',
  },
  modal_endow_title: {
    color: '#26292b',
    fontSize: 24,
    fontWeight: '600',
    lineHeight: 32,
    marginBottom: 10,
    textAlign: 'center',
  },
  modal_endow_content: {
    textAlign: 'center',
    margin: 'auto',
  },
  modal_endow_images: {
    width: Dimens.DEVICE_WIDTH * 0.8,
    height: 50,
    margin: 'auto',
    textAlign: 'center',
    alignItems: 'center',
  },
  modal_endow_img: {
    height: 50,
    width: 50,
  },
  modal_endow_exchange: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  modal_endow_name: {
    fontSize: 20,
    lineHeight: 30,
    color: '#ee0033',
    fontWeight: '600',
  },
  modal_endow_icon: {
    fontSize: 20,
    lineHeight: 30,
    color: '#ee0033',
    fontWeight: '600',
    marginHorizontal: 5,
  },
  modal_endow_des: {
    color: '#26292b',
    fontSize: 16,
    lineHeight: 24,
    marginTop: 10,
    textAlign: 'center',
  },
  modal_endow_btn: {
    backgroundColor: '#ee0033',
    marginTop: 10,
    borderRadius: 4,
  },
  modal_endow_btn_text: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '600',
    lineHeight: 24,
    paddingHorizontal: 10,
    paddingVertical: 5,
    textAlign: 'center',
  },
  // thanh toan step2
  payment_online: {
    marginTop: 20,
  },
  payment_online__sub: {
    color: '#44494d',
    fontSize: 18,
    fontWeight: '600',
    lineHeight: 28,
    marginBottom: 10,
  },
  method_payment: {
    backgroundColor: '#fff',
    borderColor: '#e4e4e4',
    borderWidth: 1,
  },
  method_payment_item: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 12,
    borderBottomColor: '#e4e4e4',
    borderBottomWidth: 1,
  },
  method_payment_item_left: {flexDirection: 'row', alignItems: 'flex-start'},
  method_payment_item_left_icon: {
    width: 30,
    height: 30,
    overflow: 'hidden',
    marginRight: 7,
  },
  method_payment_item_left_detail: {},
  method_payment_item_right: {},
  method_payment_item_left_detail_name: {
    color: '#44494d',
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: 0.02,
    lineHeight: 20,
    marginBottom: 5,
  },
  method_payment_item_left_detail_des: {
    color: '#ee0033',
    fontSize: 14,
    fontStyle: 'italic',
    lineHeight: 18,
  },
  order_payment: {
    borderColor: '#e4e4e4',
    borderWidth: 1,
    marginTop: 15,
    borderTopLeftRadius: 10,
    backgroundColor: '#fff',
  },
  order_payment_item: {
    padding: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomColor: '#e4e4e4',
    borderBottomWidth: 1,
  },
  order_payment_item_last: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  order_payment_name: {
    color: '#44494d',
    fontSize: 16,
    lineHeight: 24,
  },

  order_payment_value: {
    color: '#44494d',
    fontSize: 16,
    lineHeight: 24,
  },
  order_payment_name_last: {
    color: '#44494d',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '500',
  },
  order_payment_value_last: {
    color: '#44494d',
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '700',
  },
  note: {color: '#44494d', fontSize: 14, lineHeight: 18, marginTop: 14},
  note_icon: {marginRight: 5},
  note_icon_primary: {
    marginLeft: 5,
    color: '#ee0033',
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
  order_payment__btn: {
    backgroundColor: '#ee0033',
    borderColor: '#ee0033',
    paddingHorizontal: 10,
    paddingVertical: 7,
    marginTop: 15,
    borderRadius: 8,
  },
  order_payment__btn_primary: {
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
    letterSpacing: 0.02,
    lineHeight: 20,
    textAlign: 'center',
  },
  // so du xu
  main: {
    backgroundColor: '#f2ecf3',
    flex: 1,
  },
  blockTop: {
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: -3,
    },
    shadowRadius: 6,
    shadowOpacity: 0.1,
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 20,
    borderBottomWidth: 5,
    borderColor: '#f0eced',
  },
  blockTitle: {
    textAlign: 'center',
    fontSize: 16,
    lineHeight: 18,
    color: '#444444',
  },
  blockValue: {
    textAlign: 'center',
    fontSize: 20,
    lineHeight: 24,
    color: '#fa4214',
    marginTop: 5,
  },
  blockBody: {
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 20,
  },
  blockBodyItem: {
    flex: 1,
  },
  blockBodyIcon: {
    textAlign: 'center',
  },
  blockBodyName: {
    textAlign: 'center',
    textTransform: 'uppercase',
    marginTop: 5,
    fontSize: 14,
    lineHeight: 24,
  },
  // lich su giao dich
  lsHeader: {
    paddingHorizontal: 15,
    paddingVertical: 15,
    backgroundColor: '#f4f4f4',
  },
  lsHeaderTitle: {},
  lsBody: {},
  lsBodyItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    marginHorizontal: 5,
    paddingVertical: 10,
    borderColor: '#ccc',
    borderBottomWidth: 1,
    alignItems: 'center',
  },
  lsBodyItemLeft: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  lsBodyItemThumb: {
    width: 50,
    height: 50,
    borderRadius: 8,
    overflow: 'hidden',
    marginRight: 10,
  },
  lsBodyItemInfo: {},
  lsBodyItemTime: {
    color: '#868686',
    fontSize: 14,
    lineHeight: 20,
  },
  lsBodyItemName: {
    color: '#3f3f3f',
    fontWeight: '500',
    fontSize: 15,
    lineHeight: 20,
  },
  lsBodyItemRight: {
    alignItems: 'flex-end',
  },
  lsBodyItemPrice: {
    color: '#3f3f3f',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 20,
  },
  lsBodyItemStatus: {
    color: '#868686',
    fontSize: 14,
    lineHeight: 20,
  },
  lsBodyItemStatusFalse: {
    color: '#ff2d2d',
    fontSize: 14,
    lineHeight: 20,
  },
});
