export const Images = {
  BG1: require('@assets/images/bg1.png'),
  BG2: require('@assets/images/bg2.png'),
  BG3: require('@assets/images/bg3.png'),
  BG5: require('@assets/images/bg5.png'),
  BG4: require('@assets/images/bg4.png'),
  LOGO: require('@assets/images/logo.png'),
  LOGO1: require('@assets/images/logo1.png'),
  HTML: require('@assets/images/html.png'),
  HTMLPRO: require('@assets/images/htmlpro.png'),
  JS: require('@assets/images/js.png'),
  LTC: require('@assets/images/c.png'),
  SRM1: require('@assets/images/comingsoon1.png'),
  SRM2: require('@assets/images/commingson2.png'),
  NODEJS: require('@assets/images/nodejs.png'),
  GIFT: require('@assets/images/gift.png'),
  PAY1: require('@assets/images/img-tele-1.png'),
  PAY2: require('@assets/images/img-tele-2.png'),
  PAY3: require('@assets/images/img-tele-3.png'),
  PAY4: require('@assets/images/img-tele-4.png'),
  NODATA: require('@assets/images/nodata.png'),
};
