import Dimens from '@base/common/Dimens';
import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    flex: 1,
    color: 'rgba(0, 0, 0, 0.85)',
    fontSize: 14,
    fontFamily:
      "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, 'Noto Sans', sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji'",
    lineHeight: 15,
  },
  content: {
    paddingHorizontal: 15,
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#f5422a',
    color: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 20,
  },
  headerPerson: {
    flexDirection: 'column',
  },
  goback: {
    top: 40,
    left: 10,
    zIndex: 10,
  },
  icon: {
    color: '#fff',
  },
  headerName: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 18,
    lineHeight: 24,
  },
  bannerThumb: {
    width: '100%',
    height: 150,
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 20,
    overflow: 'hidden',
  },
  avtThumb: {
    bottom: 40,
    width: Dimens.DEVICE_WIDTH,
    height: 120,
    borderRadius: 9999,
    overflow: 'hidden',
    textAlign: 'center',
    alignItems: 'center',
  },
  avtName: {
    fontWeight: '700',
    fontSize: 20,
    lineHeight: 24,
  },
  avt: {
    margin: 'auto',
    width: 90,
    height: 90,
    borderWidth: 5,
    borderColor: '#fff',
    borderRadius: 9999,
    overflow: 'hidden',
  },
  banner: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  boxWrapper: {
    backgroundColor: '#fff',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 0},
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
    marginBottom: 20,
    paddingHorizontal: 14,
    paddingVertical: 18,
  },
  boxWrapper_title: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 8,
  },
  boxWrapperList: {
    marginTop: 10,
  },
  boxWrapperItem: {
    marginVertical: 10,
    paddingBottom: 20,
    borderBottomColor: '#d0d7de',
    borderBottomWidth: 1,
  },
  boxWrapperImgThumb: {
    width: '100%',
    height: 100,
    margin: 'auto',
    overflow: 'hidden',
    borderRadius: 17,
  },
  img: {
    width: '100%',
    height: '100%',
  },
  boxWrapper_info_title: {
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 0,
    marginTop: 10,
    color: '#333',
  },
  boxWrapper_info_desc: {
    fontSize: 15,
  },
  boxWrapper__participation: {
    flexDirection: 'row',
  },
  boxWrapper__participation_icon: {
    color: '#808990',
    marginRight: 8,
    marginTop: 2,
    width: 20,
    fontSize: 20,
  },
  boxWrapper__participation_title: {
    fontSize: 16,
    lineHeight: 20,
    color: '#333',
  },
  boxWrapper___highlight: {
    fontWeight: '600',
    marginHorizontal: 5,
  },
  info: {},
  // setting
  inputField_fieldContent: {
    marginTop: 20,
  },
  inputField_fieldContentLabel: {
    fontSize: 16,
    fontWeight: '600',
    margin: 0,
  },
  inputField_fieldContentEdit: {
    marginTop: 16,
  },
  inputField_fieldContentInput: {
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#0000000d',
    color: '#000000d6',
    fontSize: 14,
    marginBottom: 10,
    // outline: 'none',
    paddingBottom: 8,
    width: '100%',
  },
  inputField_description: {
    color: '#757575',
    fontSize: 14,
    lineHeight: 20,
  },
  inputField_fieldContentEditAvt: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'column',
  },
  inputField_fallbackAvatar_avatar: {
    width: 90,
    height: 90,
    borderRadius: 9999,
    overflow: 'hidden',
    marginLeft: 20,
  },
  inputField_main: {
    marginBottom: 100,
  },
  actionBar: {position: 'absolute', bottom: 0},
  actionBar_toggle_btn: {
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    display: 'flex',
    justifyContent: 'space-around',
    backgroundColor: '#f0f0f0',
    bottom: 0,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: -2},
    shadowOpacity: 0.2,
    shadowRadius: 7,
    height: 50,
    left: 0,
    position: 'absolute',
    right: 0,
    zIndex: 2,
  },
  actionBar_btn: {
    marginRight: 20,
  },
  actionBar_text: {
    color: '#404040',
    fontSize: 14,
    fontWeight: '600',
  },
  actionBar_icon_text: {},
  actionBar_btn_primary: {
    borderRadius: 6,
    cursor: 'pointer',
    opacity: 0.5,
    pointerEvents: 'none',
    borderWidth: 2,
    borderColor: '#f05123',
    color: '#f05123',
    padding: 8,
  },
  actionBar_text_primary: {
    color: '#f05123',
    fontSize: 14,
    fontWeight: '600',
  },
  // user
  headerUser: {
    backgroundColor: '#f03c0f',
    paddingVertical: 10,
    paddingBottom: 20,
    paddingTop: 20,
  },
  iconUser: {
    color: '#fff',
    marginHorizontal: 5,
  },

  headerTop: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    right: 10,
  },
  headerTopNoti: {
    right: 10,
  },
  headerBody: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerThumb: {
    width: 40,
    height: 40,
    overflow: 'hidden',
    borderRadius: 999,
  },
  headerInfo: {
    marginLeft: 10,
    position: 'relative',
  },
  headerSubName: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '500',
  },
  main: {},
  mainItem: {
    flexDirection: 'row',
    paddingVertical: 10,
    paddingHorizontal: 15,
    justifyContent: 'space-between',
    borderBottomColor: '#e7e7e7',
    borderBottomWidth: 1,
  },
  mainItemLeft: {
    flexDirection: 'row',
  },
  mainItemTilte: {
    fontSize: 15,
    fontWeight: '500',
    color: '#333',
  },
  mainItemRight: {},
  box1: {
    backgroundColor: '#fff',
    borderTopWidth: 5,
    borderTopColor: '#e3e3e3',
  },
  icon1: {
    color: '#eca8af',
    marginHorizontal: 7,
    fontWeight: '500',
  },
  iconArr: {
    color: '#838383',
    marginHorizontal: 7,
    fontWeight: '500',
  },
});
